### PR TITLE
fix: upload corresponding latest snapshot sha256sum 

### PR DESCRIPTION
**Pull request by samuelarogbonlo**
**Summary of changes**
Changes introduced in this pull request:
- upload corresponding latest snapshot sha256sum 

**Reference issue to close (if applicable)**

part #370 

**Other information and links**

### CODE REVIEW

**Review by lemmih — CHANGES_REQUESTED** [review]
Let's enumerate the files to be uploaded rather than using a wildcard.

**Comment by samuelarogbonlo** [comment]
> Let's enumerate the files to be uploaded rather than using a wildcard.

updated, @lemmih what do you think ?

**Comment by LesnyRumcajs** [comment]
@lemmih Looking at https://github.com/ChainSafe/forest-iac/blob/main/cf/prune-latest/src/index.ts, it seems that adding corresponding checksum files would decrease the number of recent snapshots by half. Are we okay with that? Or should that worker be updated accordingly?

**Comment by lemmih** [comment]
> @lemmih Looking at https://github.com/ChainSafe/forest-iac/blob/main/cf/prune-latest/src/index.ts, it seems that adding corresponding checksum files would decrease the number of recent snapshots by half. Are we okay with that? Or should that worker be updated accordingly?

If the Infra team is ready to take over then we don't have to worry about retention. Let's see what Josh at the meeting later today. If they need more time, we'll bump our retention (which is still quite a bit lower than required by the contract, iirc).

**Review by hanabi1224 — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
Service snapshot discontinued in favour of infra snapshot service.

**Pull request closed without merging**
