### PR TITLE
fix: wait for cloud-init to finish

### PR DESCRIPTION
**Pull request by lemmih**
**Summary of changes**
Changes introduced in this pull request:
- Cloud-init clashes with our init script. We should wait for the machine to finish initializing before running our own script.

**Reference issue to close (if applicable)**

Closes

**Other information and links**

### CODE REVIEW

**Review by elmattic — APPROVED** [review]

**Review by LesnyRumcajs — COMMENTED** [review]
Shall we do the same for the sync check?

**Comment by lemmih** [comment]
> Shall we do the same for the sync check?

Yes, I think it'll solve a lot of the random failures we've been seeing. We can probably also remove the silly sleep at the end of the initialization.

**Comment by LesnyRumcajs** [comment]
> > Shall we do the same for the sync check?
> 
> Yes, I think it'll solve a lot of the random failures we've been seeing. We can probably also remove the silly sleep at the end of the initialization.

Let's do it, then.

**Comment by lemmih** [comment]
> > > Shall we do the same for the sync check?
> > 
> > 
> > Yes, I think it'll solve a lot of the random failures we've been seeing. We can probably also remove the silly sleep at the end of the initialization.
> 
> Let's do it, then.

Done.

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
