### PR TITLE
feat: separate dev and prod environments for daily snapshots

### PR DESCRIPTION
**Pull request by lemmih**
**Summary of changes**
Changes introduced in this pull request:
- add separate terraform file for setting up a development deployment that is separate from the production deployment.

**Reference issue to close (if applicable)**

Closes

**Other information and links**

### CODE REVIEW

**Review by LesnyRumcajs — APPROVED** [review]
Given that prod is in `prod/`, how about moving dev to `dev/` for consistency?

**Comment by lemmih** [comment]
> Given that prod is in `prod/`, how about moving dev to `dev/` for consistency?

I kind of like that `prod/` is hidden away and the dev files are always the first thing you see.

**Comment by lemmih** [comment]
> what about the same set-up for other services?

That will come later.

**Comment by LesnyRumcajs** [comment]
@lemmih mergio?

**Comment by lemmih** [comment]
> @lemmih mergio?

Yeah, just have to fix the merge conflict.

**Comment by lemmih** [comment]
> > @lemmih mergio?
> 
> Yeah, just have to fix the merge conflict.

Fixed. That was a lot easier than I had feared.

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
