### PR TITLE
downgrade snapshot service to v0.15.2

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
**Summary of changes**
Changes introduced in this pull request:
- the `v0.16.0` _Rottenmelon_ may have a performance regression. For the time being, we could use `v0.15.2` _Defenestration_, given we are past the Watermelon fixes epochs anyway with the recent snapshots.

**Reference issue to close (if applicable)**

Closes

**Other information and links**

### CODE REVIEW

**Review by lemmih — APPROVED** [review]

**Review by lemmih — CHANGES_REQUESTED** [review]
The snapshot server has synced, and a snapshot is being exported. Let's hold off this PR for now.

**Comment by LesnyRumcajs** [comment]
I did a single check of ~80 epochs between `0.16.0` and `0.15.2`, and there was a 20% difference (`0.16.0` being slower) with a bunch of `sending on a closed channel` warnings. It's not decisive, though, the `0.16.0` may have gotten better peers.

**Comment by LesnyRumcajs** [comment]
@lemmih as confirmed by @ruseinov, https://github.com/ChainSafe/forest/pull/3683 caused the regression in performance so I believe we should go ahead with the downgrade for now.

**Comment by ruseinov** [comment]
@LesnyRumcajs perhaps instead of reverting we should do a hotfix to `0.16`? 
The problem is we already have some snapshots that don't work with `0.15.2` version..

**Comment by LesnyRumcajs** [comment]
It shouldn't matter really. The snapshot service is bootstrapping from newer snapshots anyway.

**Comment by ruseinov** [comment]
> It shouldn't matter really. The snapshot service is bootstrapping from newer snapshots anyway.

Roger that. 
I had issues with bootstrapping `0.15.2` with the newest calibnet snapshot.

**Comment by ruseinov** [comment]
We're holding off on this PR according to @lemmih, not sure if we need to merge it then or not.

**Comment by LesnyRumcajs** [comment]
Hopefully, superseded by https://github.com/ChainSafe/forest-iac/pull/342

**Pull request closed without merging**
